personalkit:
  # 压缩图片保存路径
  compressPath: /Users/zhoukai/project/my-project/personalKit/compressImg
  # 百度翻译api地址
  baiduTranslationUrl: "http://api.fanyi.baidu.com/api/trans/vip/translate"
  # 百度appId
  appId: 20210916000946790
  # 百度appKey
  appKey: tW5PYm3kRGU_V4kJglSv
  # 高德key
  gaoDeKey: 06c0ce4be4379ac5d4072f01bbbe0797